version: "3"
services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user1
      - DB_PASSWORD=passwd
      - DB_NAME=movie_booking

  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8082:80"
    volumes:
      - ./public:/var/www/html/
    restart: always

  mysql:
    image: mysql:8.0
    platform: linux/x86_64 # Adjust this if you're using ARM architecture
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: movie_booking
      MYSQL_USER: user1
      MYSQL_PASSWORD: passwd
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']

volumes:
  db_data: